settings:
  A: BLOCKELOT.COM -> Saving stuff in minecraft the easy way!    
  Description: A tool to allow players to cut and paste across servers.
  HomePage: Http://www.Blockelot.com
  Contact: Vince@Fairfieldtek.com
  config:
    maxclipboardsize: 1000000000
    BaseUri: http://Blockelot.com/api/worldeditor/v1/
  perms:
    user: Blockelot.WorldEditor.User
    clear: Blockelot.WorldEditor.User.Clear
    clearhistory: Blockelot.WorldEditor.User.ClearHistory
    size: Blockelot.WorldEditor.User.Size
    print: Blockelot.WorldEditor.User.Print
    select: Blockelot.WorldEditor.User.Select
    editor: Blockelot.WorldEditor.Editor
    copy: Blockelot.WorldEditor.Editor.Copy
    delete: Blockelot.WorldEditor.Editor.Delete
    distr: Blockelot.WorldEditor.Editor.Distr
    paste: Blockelot.WorldEditor.Editor.Paste
    stripmine: Blockelot.WorldEditor.Editor.StripMine
    undo: Blockelot.WorldEditor.Editor.Undo
    filesystem: Blockelot.FileSystem.User
